### ISSUE TITLE
websocket based handler throwing multiple exceptions with Facebook

### ISSUE THREAD

**Issue by sherjil-ahmed** [TechnikEmpire/CitadelCore#74]
I had issues while filtering facebook, then I see you have made lots fo changes in web-socket based handler. I upgraded your code in my solution. Now Following exceptions are being raised frequently and consistently from FilterWebsocketHandler when filtering on facebook.com

The operation was canceled.
Aborted, Cannot access a disposed object. Object name: 'SslStream'.

Unable to connect to the remote server   

The remote party closed the WebSocket connection without completing the close handshake.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
An existing connection was forcibly closed by the remote host   
Concurrent reads or writes are not supported.

**Comment by TechnikEmpire** [comment]
Interesting. Thanks for reporting.

Unfortunately I'm on version 5 of this engine in private development so it would be hard for me to work backwards here.

It appears however that the issue can be solved by wrapping the calls to each socket in a socket-specific lock object. I'll see if I can get that integrated here because I'll definitely want that fix privately.

I'm not sure what app is attempting concurrent IO, that's quite odd. Perhaps it is my code though, which again can be solved with independent locks.

**Comment by sherjil-ahmed** [comment]
Thanks for the response. May I know how I can get beniffit of your private repo (I can pay for it, if possible) 
I need much stable version. 

Also I have also made some modification in your code (under my repo) so I can pay if you can look into my repo to fix websocket issues

**Comment by TechnikEmpire** [comment]
@sherjil-ahmed Honestly I haven't even thought about licensing the private version. The private version is for an upcoming product. You can email me at info@technikempire.com, I'd be interested in hearing about your project. I'd be open to suggestions regarding licensing the private code because as I said, I haven't even considered it.

As far as the websocket fix, I'll implement that here soon, probably within the next few days.

**Comment by sherjil-ahmed** [comment]
tried  wrapping the calls to each socket in a socket-specific lock object (using SemaphoreSlim WaitAsync/Release) but still getting same exceptions frequently and consistently.

**Comment by sherjil-ahmed** [comment]
I have checked it with facebook and facebook is displayed with broken UI.
Also getting exception in log file.

Ignoring on second glance means,? Should not furthur read or write on the context which causes exception ?
Is that u mean

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TechnikEmpire** [comment]
I don't see any broken UI on Facebook, and last time I checked this code was passing the autobahn test suite.

What I mean regarding ignoring is that many thrown exceptions are not really errors. For example kestrel throws socket closed/connection reset exceptions like crazy, but its not actually an error. You can repeat this by just refreshing your browser in the middle of a load.

Are you loading Facebook in another language perhaps? I wonder if Intl is part of the problem here because I havbt seen any errors that break Facebook.

**Comment by sherjil-ahmed** [comment]
Dear Jesse Nicholson,
I was trying to build and run one of your repo "Filter-Windows" (https://github.com/TechnikEmpire/Filter-Windows). 
I am able to build it (configured UI Project & Service Project as multiple startups) after a small tweak.

The first screen is asking for user id and password. Can you tell me what are these credentials ? so that I can walk through with the UI to explore the functionality.
 

Thanks
Sherjil Ahmed

**Comment by TechnikEmpire** [comment]
Note that Filter-Windows is an application I made for a specific group in the united states/canada. I was not finished the work, when they decided for purely tribal and monetary reasons to oust me from the project I had created. They figured they could handle it now, so after duping me into working at a drastically reduced rate under the banner of comradery and having me spend significant money on hardware for further development, they silently started blocking out of contributing code. They they went out of their way to badmouth me and my open source code, trying to kill my business, so they could have my profits.

Since I was the sole innovator of the software, the project is dying is a slow and ugly death. If you look back at the repo I forked this project from, you can see it's been in a death spiral of the developer(s) just randomly dumping non-innovative stuff into the code base, usually copy and pasted from other people. Their sole goal is to vacuum up swaths of money from their users, who are compelled to use their software.

I would highly recommend that you do not use this software. Their primary developer follows people who know what they're doing on Github and begs them for help. It's riddled with bugs that I have long fixed ages ago, and the developer(s) have not found anyone with enough skill to fix them for them. Furthermore, these people have stolen copyrighted code and purged the licenses, and profited from it. So there's a high chance their code base is polluted with copyright infringement.

The credentials you're being asked for are their web server credentials. You would need to pay them money to get an account.

You can easily create a superior software by looking at the CitadelCore.Windows example project, stuffing it into a service using TopShelf, and then using open source IPC libraries to communicate between a GUI and your newly minted filtering service.
